version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: testseriesdb
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
  app:
    build: .
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testseriesdb?useSSL=false
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
